/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2025-03-10 15:39:34 - DO NOT EDIT!
 * This file was automatically generated by mysql-plain-dao
 */

export type enum_role = 'admin' | 'user' | 'guest';
export type enum_status = 'draft' | 'published' | 'archived';

export interface Category {
    id: number;
    name: string;
    sort_order?: number | null;
    created_at?: Date | null;
    updated_at?: Date | null;
}

export type InsertCategory = Omit<Category, 'id'>;
