/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2025-03-10 15:39:34
 * This file was automatically generated by mysql-plain-dao.
 * Feel free to add your custom database access methods to this class.
 */

import type { Category, InsertCategory } from './Category';
import { BaseDao } from '../../dao/BaseDao';
export class CategoryDao extends BaseDao<Category, InsertCategory> {
    constructor() {
        super({
            table_name: 'category',
        });
    }

    // Place your custom database access methods here
}
