/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2025-03-04 16:57:36 - DO NOT EDIT!
 * This file was automatically generated by mysql-plain-dao
 */
export type enum_role = 'admin' | 'user' | 'guest';
export type enum_status = 'draft' | 'published' | 'archived';

export interface News {
    id: number;
    title: string;
    content: string;
    author_id: number;
    status?: enum_status | null;
    view_count?: number | null;
    published_at?: Date | null;
    created_at?: Date | null;
    updated_at?: Date | null;
}
