/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2025-03-04 16:57:36 - DO NOT EDIT!
 * This file was automatically generated by mysql-plain-dao
 */
export type enum_role = 'admin' | 'user' | 'guest';
export type enum_status = 'draft' | 'published' | 'archived';

export interface User {
    id: number;
    uuid: string;
    username: string;
    email: string;
    password_hash: string;
    first_name?: string | null;
    last_name?: string | null;
    phone?: string | null;
    is_active?: boolean | null;
    role?: enum_role | null;
    last_login?: Date | null;
    created_at?: Date | null;
    updated_at?: Date | null;
}
