/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2025-03-04 16:57:36 - DO NOT EDIT!
 * This file was automatically generated by mysql-plain-dao
 */
export type enum_role = 'admin' | 'user' | 'guest';
export type enum_status = 'draft' | 'published' | 'archived';

export interface UserPermission {
    id: number;
    user_id: number;
    permission_name: string;
    resource_type: string;
    resource_id?: string | null;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    created_at?: Date | null;
    updated_at?: Date | null;
}

export type InsertUserPermission = Omit<UserPermission, 'id'>;
