services:
  mysql_test:
    image: mariadb:11.2
    container_name: mysql_test
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test_db
    volumes:
      - ./src/__tests__/sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20

  jest_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: jest_test
    working_dir: /app
    volumes:
      # - .:/app
      - /app/node_modules
      - ./docker-logs:/root/.npm/_logs
    environment:
      - DB_HOST=mysql_test
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=test_db
      - DB_CONNECTION_LIMIT=10
      - DB_QUEUE_LIMIT=0
      - DB_WAIT_FOR_CONNECTIONS=true
      - DEBUG=DAO
      - NODE_ENV=test-docker
      - DOCKER_CLIENT_TIMEOUT=300
      - COMPOSE_HTTP_TIMEOUT=300
      - WAIT_HOSTS=mysql_test:3306
      - WAIT_TIMEOUT=60
    command: >
      bash -c "
        echo 'All files in /app (node_modules is ignored here)' > /root/.npm/_logs/files.log &&
        tree -a -I 'node_modules|.git' /app >> /root/.npm/_logs/files.log &&
        set -o pipefail &&
        pnpm test-docker 2>&1 | tee /root/.npm/_logs/jest-output.log
      "
    depends_on:
      mysql_test:
        condition: service_healthy
    restart: on-failure:3
    stop_grace_period: 60s
