import fs from 'fs'
import { type Options as ITFOptions, processString } from 'typescript-formatter'
import {
    getDatabase,
    toCamelCase,
    transformColumnName,
    transformTypeName
} from './common'
import type { CliOptions, Database, TableDefinition } from './Types'

export async function generateAndWriteModels(
    db: Database,
    tables: string[],
    schema: string,
    options: CliOptions
): Promise<void> {
    if (options.generateType === 'model' || options.generateType === 'all') {
        for (const table of tables) {
            const modelName = toCamelCase(table)
            let output = ''

            if (options.writeHeader) {
                output += buildHeader(db, [table], schema, options)
            }

            // Generate enum types
            const enumTypes = generateEnumType(await db.getEnumTypes(schema, table), options)
            output += enumTypes

            // Add newline between enum types and interface
            if (enumTypes) {
                output += '\n'
            }

            // Generate model interface for this table
            const modelContent = await typescriptOfTable(db, table, schema, options)
            output += modelContent

            const formattedOutput = await formatTypeScript(output)

            // Generate file name based on table name
            const fileName = `${modelName}.ts`

            // Use modelDir if specified, otherwise use outputDir
            const outputDir = options.modelDir || options.outputDir
            if (!outputDir) {
                throw new Error('No output directory specified for model generation')
            }
            const outputPath = `${outputDir}/${fileName}`

            // Ensure output directory exists
            fs.mkdirSync(outputDir, { recursive: true })

            fs.writeFileSync(outputPath, formattedOutput)
            console.log(`✅ Generated model file: ${fileName}`)
        }
    }
}

function getTime() {
    let padTime = (value: number) => `0${value}`.slice(-2)
    let time = new Date()
    const yyyy = time.getFullYear()
    const MM = padTime(time.getMonth() + 1)
    const dd = padTime(time.getDate())
    const hh = padTime(time.getHours())
    const mm = padTime(time.getMinutes())
    const ss = padTime(time.getSeconds())
    return `${yyyy}-${MM}-${dd} ${hh}:${mm}:${ss}`
}

export function buildHeader(db: Database, tables: string[], schema: string | null, options: CliOptions): string {

    return `        /**
         * AUTO-GENERATED FILE @ ${getTime()} - DO NOT EDIT THIS FILE!
         * This file was automatically generated by mysql-plain-dao
         */

`
}

export async function typescriptOfTable(db: Database | string,
    table: string,
    schema: string,
    options: CliOptions) {
    if (typeof db === 'string') {
        db = getDatabase(db)
    }

    let interfaces = ''
    let tableTypes = await db.getTableTypes(table, schema, options)
    let tableMetadata = await (db as Database).getTableDefinition(table, schema)

    // Add table comment if available
    if (tableMetadata.comment) {
        interfaces += `\n/**\n`
        interfaces += ` * ${tableMetadata.comment}\n`
        interfaces += ` */\n`
    }

    // Generate main interface with column comments
    interfaces += generateTableTypes(table, tableTypes, tableMetadata.columns, options)

    // Check if we need to generate InsertModel type
    const tableDefinition = tableMetadata.columns;

    // Check for integer ID column
    const integerIdColumn = Object.entries(tableDefinition).find(([name, def]) =>
        name.toLowerCase() === 'id' &&
        def.isPrimaryKey &&
        ['int', 'bigint', 'integer'].includes(def.udtName.toLowerCase())
    );

    // Check for UUID column
    const uuidColumn = Object.entries(tableDefinition).find(([name, def]) => {
        const isStringType = ['char', 'varchar'].includes(def.udtName.toLowerCase());
        return name.toLowerCase() === 'uuid' &&
            isStringType &&
            (def.isUnique || def.isPrimaryKey);
    });

    // Generate InsertModel type if needed
    if (integerIdColumn || uuidColumn) {
        const tableName = toCamelCase(table);
        const omitFields = [];

        if (integerIdColumn) {
            omitFields.push(`'${integerIdColumn[0]}'`);
        }
        if (uuidColumn) {
            omitFields.push(`'${uuidColumn[0]}'`);
        }

        if (omitFields.length > 0) {
            interfaces += `\n\n/** Type for inserting new records (without ${omitFields.join(' and ')}) */\n`;
            interfaces += `export type Insert${tableName} = Omit<${tableName}, ${omitFields.join(' | ')}>;\n`;
        }
    }

    return interfaces;
}

export async function formatTypeScript(content: string): Promise<string> {
    const formatterOption: ITFOptions = {
        replace: false,
        verify: false,
        tsconfig: true,
        tslint: true,
        editorconfig: true,
        tsfmt: true,
        vscode: false,
        tsconfigFile: null,
        tslintFile: null,
        vscodeFile: null,
        tsfmtFile: null
    }

    const processedResult = await processString('schema.ts', content, formatterOption)
    return processedResult.dest
}

function generateTableTypes(
    tableNameRaw: string,
    tableDefinition: TableDefinition,
    columnsWithComments: TableDefinition,
    options: CliOptions
) {
    const tableName = toCamelCase(tableNameRaw)
    let fields = ''

    Object.entries(tableDefinition).forEach(([columnNameRaw, column]) => {
        const columnName = transformColumnName(columnNameRaw)
        const normalizedName = normalizeName(columnName, options)
        const type = column.tsType || 'any'
        const nullable = column.nullable ? ' | null' : ''
        const optionalModifier = column.nullable ? '?' : ''

        // Add column comment if available
        const columnComment = columnsWithComments[columnNameRaw]?.comment
        if (columnComment) {
            fields += `    /** ${columnComment} */\n`
        }

        fields += `    ${normalizedName}${optionalModifier}: ${type}${nullable};\n`
    })

    return `export interface ${tableName} {
${fields}}`
}

export function generateEnumType(enumObject: any, options: CliOptions) {
    let enumString = ''
    for (let enumNameRaw in enumObject) {
        const enumName = transformTypeName(enumNameRaw)
        enumString += `export type ${enumName} = `
        enumString += enumObject[enumNameRaw].map((v: string) => `'${v}'`).join(' | ')
        enumString += ';\n'
    }
    return enumString
}

function nameIsReservedKeyword(name: string): boolean {
    const reservedKeywords = [
        'string',
        'number',
        'package'
    ]
    return reservedKeywords.indexOf(name) !== -1
}

export function normalizeName(name: string, options: CliOptions): string {
    if (nameIsReservedKeyword(name)) {
        return name + '_'
    } else {
        return name
    }
}

