/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2025-03-04 16:57:36 - DO NOT EDIT!
 * This file was automatically generated by mysql-plain-dao
 */
export type enum_role = 'admin' | 'user' | 'guest';
export type enum_status = 'draft' | 'published' | 'archived';

export interface Book {
    uuid: string;
    title: string;
    author_id: number;
    created_at?: Date | null;
    updated_at?: Date | null;
}
