import fs from 'fs'
import { Options as ITFOptions, processString } from 'typescript-formatter'
import { getDatabase } from './common'
import { CliOptions, Database } from './Types'
import { generateEnumType, generateTableInterface, generateTableTypes } from './common'

export async function generateAndWriteModels(
    db: Database,
    tables: string[],
    schema: string,
    options: CliOptions
): Promise<void> {
    // Generate and write files based on generation type
    if (options.generateType === 'model' || options.generateType === 'all') {

        let output = '/* tslint:disable */\n\n'

        if (options.writeHeader) {
            output += buildHeader(db, tables, schema, options)
        }

        // Generate enum types
        const enumTypes = generateEnumType(await db.getEnumTypes(schema), options)
        output += enumTypes

        // Generate model interfaces
        const modelContent = await generateModels(db, tables, schema, options)
        output += modelContent

        const formattedOutput = await formatTypeScript(output)

        const outputPath = `${options.modelDir}/${options.outputFile}`
        // Ensure output directories exist
        if (options.modelDir) {
            fs.mkdirSync(options.modelDir, { recursive: true });
        }
        fs.writeFileSync(outputPath, formattedOutput)

    }

}



function getTime() {
    let padTime = (value: number) => `0${value}`.slice(-2)
    let time = new Date()
    const yyyy = time.getFullYear()
    const MM = padTime(time.getMonth() + 1)
    const dd = padTime(time.getDate())
    const hh = padTime(time.getHours())
    const mm = padTime(time.getMinutes())
    const ss = padTime(time.getSeconds())
    return `${yyyy}-${MM}-${dd} ${hh}:${mm}:${ss}`
}

export function buildHeader(db: Database, tables: string[], schema: string | null, options: CliOptions): string {
    let commands = ['schemats', 'generate', '-c', db.connectionString.replace(/:\/\/.*@/, '://username:password@')]
    if (options.camelCase) commands.push('-C')
    if (tables.length > 0) {
        tables.forEach((t: string) => {
            commands.push('-t', t)
        })
    }
    if (schema) {
        commands.push('-s', schema)
    }

    return `
        /**
         * AUTO-GENERATED FILE @ ${getTime()} - DO NOT EDIT!
         *
         * This file was automatically generated by schemats}
         * $ ${commands.join(' ')}
         *
         */

    `
}

export async function typescriptOfTable(db: Database | string,
    table: string,
    schema: string,
    options: CliOptions) {
    if (typeof db === 'string') {
        db = getDatabase(db)
    }

    let interfaces = ''
    let tableTypes = await db.getTableTypes(table, schema, options)
    interfaces += generateTableTypes(table, tableTypes, options)
    interfaces += generateTableInterface(table, tableTypes, options)
    return interfaces
}

async function generateModels(
    db: Database,
    tables: string[],
    schema: string,
    options: CliOptions
): Promise<string> {
    const interfacePromises = tables.map((table) =>
        typescriptOfTable(db, table, schema, options)
    )
    return Promise.all(interfacePromises).then(tsOfTable => tsOfTable.join(''))
}

export async function formatTypeScript(content: string): Promise<string> {
    const formatterOption: ITFOptions = {
        replace: false,
        verify: false,
        tsconfig: true,
        tslint: true,
        editorconfig: true,
        tsfmt: true,
        vscode: false,
        tsconfigFile: null,
        tslintFile: null,
        vscodeFile: null,
        tsfmtFile: null
    }

    const processedResult = await processString('schema.ts', content, formatterOption)
    return processedResult.dest
}