import fs from 'fs'
import { type Options as ITFOptions, processString } from 'typescript-formatter'
import {
    generateEnumType,
    generateTableInterface,
    generateTableTypes,
    getDatabase,
    formatNameWithCase
} from './common.js'
import type { CliOptions, Database } from './Types.js'

export async function generateAndWriteModels(
    db: Database,
    tables: string[],
    schema: string,
    options: CliOptions
): Promise<void> {
    if (options.generateType === 'model' || options.generateType === 'all') {
        for (const table of tables) {
            let output = '/* tslint:disable */\n\n'

            if (options.writeHeader) {
                output += buildHeader(db, [table], schema, options)
            }

            // Generate enum types
            const enumTypes = generateEnumType(await db.getEnumTypes(schema), options)
            output += enumTypes

            // Generate model interface for this table
            const modelContent = await typescriptOfTable(db, table, schema, options)
            output += modelContent

            const formattedOutput = await formatTypeScript(output)

            // Generate file name based on table name
            const modelName = formatNameWithCase(table)
            const fileName = `${modelName}Model.ts`

            // Use modelDir if specified, otherwise use outputDir
            const outputDir = options.modelDir || options.outputDir
            if (!outputDir) {
                throw new Error('No output directory specified for model generation')
            }
            const outputPath = `${outputDir}/${fileName}`

            // Ensure output directory exists
            fs.mkdirSync(outputDir, { recursive: true })

            fs.writeFileSync(outputPath, formattedOutput)
        }
    }
}

function getTime() {
    let padTime = (value: number) => `0${value}`.slice(-2)
    let time = new Date()
    const yyyy = time.getFullYear()
    const MM = padTime(time.getMonth() + 1)
    const dd = padTime(time.getDate())
    const hh = padTime(time.getHours())
    const mm = padTime(time.getMinutes())
    const ss = padTime(time.getSeconds())
    return `${yyyy}-${MM}-${dd} ${hh}:${mm}:${ss}`
}

export function buildHeader(db: Database, tables: string[], schema: string | null, options: CliOptions): string {
    let commands = ['schemats', 'generate', '-c', db.connectionString.replace(/:\/\/.*@/, '://username:password@')]
    if (tables.length > 0) {
        tables.forEach((t: string) => {
            commands.push('-t', t)
        })
    }
    if (schema) {
        commands.push('-s', schema)
    }

    return `
        /**
         * AUTO-GENERATED FILE @ ${getTime()} - DO NOT EDIT!
         *
         * This file was automatically generated by schemats}
         * $ ${commands.join(' ')}
         *
         */
    `
}

export async function typescriptOfTable(db: Database | string,
    table: string,
    schema: string,
    options: CliOptions) {
    if (typeof db === 'string') {
        db = getDatabase(db)
    }

    let interfaces = ''
    let tableTypes = await db.getTableTypes(table, schema, options)
    interfaces += generateTableTypes(table, tableTypes, options)
    interfaces += generateTableInterface(table, tableTypes, options)
    return interfaces
}

export async function formatTypeScript(content: string): Promise<string> {
    const formatterOption: ITFOptions = {
        replace: false,
        verify: false,
        tsconfig: true,
        tslint: true,
        editorconfig: true,
        tsfmt: true,
        vscode: false,
        tsconfigFile: null,
        tslintFile: null,
        vscodeFile: null,
        tsfmtFile: null
    }

    const processedResult = await processString('schema.ts', content, formatterOption)
    return processedResult.dest
}