name: Release & Publish

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  test:
    uses: ./.github/workflows/test.yml # 调用测试工作流

  release:
    needs: test # 等待测试完成后再执行发布
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
          
      - name: Publish to NPM
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 